// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Infrastructure.Data;

#nullable disable

namespace Nexus.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240814234519_20240815_Initial")]
    partial class _20240815_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Mine", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GainMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("Mines", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SolarSystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolarSystemId");

                    b.ToTable("Planets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SolarSystemId = 1
                        },
                        new
                        {
                            Id = 2,
                            SolarSystemId = 1
                        },
                        new
                        {
                            Id = 3,
                            SolarSystemId = 1
                        },
                        new
                        {
                            Id = 4,
                            SolarSystemId = 1
                        },
                        new
                        {
                            Id = 5,
                            SolarSystemId = 1
                        },
                        new
                        {
                            Id = 6,
                            SolarSystemId = 1
                        },
                        new
                        {
                            Id = 7,
                            SolarSystemId = 1
                        },
                        new
                        {
                            Id = 8,
                            SolarSystemId = 1
                        },
                        new
                        {
                            Id = 9,
                            SolarSystemId = 1
                        },
                        new
                        {
                            Id = 10,
                            SolarSystemId = 2
                        },
                        new
                        {
                            Id = 11,
                            SolarSystemId = 2
                        },
                        new
                        {
                            Id = 12,
                            SolarSystemId = 2
                        },
                        new
                        {
                            Id = 13,
                            SolarSystemId = 3
                        },
                        new
                        {
                            Id = 14,
                            SolarSystemId = 3
                        },
                        new
                        {
                            Id = 15,
                            SolarSystemId = 3
                        },
                        new
                        {
                            Id = 16,
                            SolarSystemId = 4
                        },
                        new
                        {
                            Id = 17,
                            SolarSystemId = 4
                        },
                        new
                        {
                            Id = 18,
                            SolarSystemId = 4
                        },
                        new
                        {
                            Id = 19,
                            SolarSystemId = 4
                        },
                        new
                        {
                            Id = 20,
                            SolarSystemId = 4
                        },
                        new
                        {
                            Id = 21,
                            SolarSystemId = 4
                        },
                        new
                        {
                            Id = 22,
                            SolarSystemId = 4
                        },
                        new
                        {
                            Id = 23,
                            SolarSystemId = 5
                        },
                        new
                        {
                            Id = 24,
                            SolarSystemId = 5
                        },
                        new
                        {
                            Id = 25,
                            SolarSystemId = 5
                        },
                        new
                        {
                            Id = 26,
                            SolarSystemId = 5
                        },
                        new
                        {
                            Id = 27,
                            SolarSystemId = 5
                        },
                        new
                        {
                            Id = 28,
                            SolarSystemId = 5
                        },
                        new
                        {
                            Id = 29,
                            SolarSystemId = 5
                        },
                        new
                        {
                            Id = 30,
                            SolarSystemId = 5
                        },
                        new
                        {
                            Id = 31,
                            SolarSystemId = 6
                        },
                        new
                        {
                            Id = 32,
                            SolarSystemId = 6
                        },
                        new
                        {
                            Id = 33,
                            SolarSystemId = 6
                        },
                        new
                        {
                            Id = 34,
                            SolarSystemId = 6
                        },
                        new
                        {
                            Id = 35,
                            SolarSystemId = 6
                        },
                        new
                        {
                            Id = 36,
                            SolarSystemId = 7
                        },
                        new
                        {
                            Id = 37,
                            SolarSystemId = 7
                        },
                        new
                        {
                            Id = 38,
                            SolarSystemId = 7
                        },
                        new
                        {
                            Id = 39,
                            SolarSystemId = 7
                        },
                        new
                        {
                            Id = 40,
                            SolarSystemId = 8
                        },
                        new
                        {
                            Id = 41,
                            SolarSystemId = 8
                        },
                        new
                        {
                            Id = 42,
                            SolarSystemId = 8
                        },
                        new
                        {
                            Id = 43,
                            SolarSystemId = 8
                        },
                        new
                        {
                            Id = 44,
                            SolarSystemId = 8
                        },
                        new
                        {
                            Id = 45,
                            SolarSystemId = 8
                        },
                        new
                        {
                            Id = 46,
                            SolarSystemId = 8
                        },
                        new
                        {
                            Id = 47,
                            SolarSystemId = 8
                        },
                        new
                        {
                            Id = 48,
                            SolarSystemId = 8
                        },
                        new
                        {
                            Id = 49,
                            SolarSystemId = 9
                        },
                        new
                        {
                            Id = 50,
                            SolarSystemId = 9
                        },
                        new
                        {
                            Id = 51,
                            SolarSystemId = 9
                        },
                        new
                        {
                            Id = 52,
                            SolarSystemId = 9
                        },
                        new
                        {
                            Id = 53,
                            SolarSystemId = 9
                        },
                        new
                        {
                            Id = 54,
                            SolarSystemId = 9
                        },
                        new
                        {
                            Id = 55,
                            SolarSystemId = 9
                        },
                        new
                        {
                            Id = 56,
                            SolarSystemId = 9
                        },
                        new
                        {
                            Id = 57,
                            SolarSystemId = 10
                        },
                        new
                        {
                            Id = 58,
                            SolarSystemId = 10
                        },
                        new
                        {
                            Id = 59,
                            SolarSystemId = 10
                        },
                        new
                        {
                            Id = 60,
                            SolarSystemId = 10
                        });
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsColonized")
                        .HasColumnType("bit");

                    b.Property<int?>("PlanetId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId");

                    b.HasIndex("UserId");

                    b.ToTable("Regions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsColonized = false,
                            PlanetId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsColonized = false,
                            PlanetId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsColonized = false,
                            PlanetId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsColonized = false,
                            PlanetId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsColonized = false,
                            PlanetId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsColonized = false,
                            PlanetId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsColonized = false,
                            PlanetId = 3
                        },
                        new
                        {
                            Id = 8,
                            IsColonized = false,
                            PlanetId = 3
                        },
                        new
                        {
                            Id = 9,
                            IsColonized = false,
                            PlanetId = 3
                        },
                        new
                        {
                            Id = 10,
                            IsColonized = false,
                            PlanetId = 4
                        },
                        new
                        {
                            Id = 11,
                            IsColonized = false,
                            PlanetId = 4
                        },
                        new
                        {
                            Id = 12,
                            IsColonized = false,
                            PlanetId = 4
                        },
                        new
                        {
                            Id = 13,
                            IsColonized = false,
                            PlanetId = 5
                        },
                        new
                        {
                            Id = 14,
                            IsColonized = false,
                            PlanetId = 5
                        },
                        new
                        {
                            Id = 15,
                            IsColonized = false,
                            PlanetId = 5
                        },
                        new
                        {
                            Id = 16,
                            IsColonized = false,
                            PlanetId = 6
                        },
                        new
                        {
                            Id = 17,
                            IsColonized = false,
                            PlanetId = 6
                        },
                        new
                        {
                            Id = 18,
                            IsColonized = false,
                            PlanetId = 6
                        },
                        new
                        {
                            Id = 19,
                            IsColonized = false,
                            PlanetId = 7
                        },
                        new
                        {
                            Id = 20,
                            IsColonized = false,
                            PlanetId = 7
                        },
                        new
                        {
                            Id = 21,
                            IsColonized = false,
                            PlanetId = 7
                        },
                        new
                        {
                            Id = 22,
                            IsColonized = false,
                            PlanetId = 8
                        },
                        new
                        {
                            Id = 23,
                            IsColonized = false,
                            PlanetId = 8
                        },
                        new
                        {
                            Id = 24,
                            IsColonized = false,
                            PlanetId = 8
                        },
                        new
                        {
                            Id = 25,
                            IsColonized = false,
                            PlanetId = 9
                        },
                        new
                        {
                            Id = 26,
                            IsColonized = false,
                            PlanetId = 9
                        },
                        new
                        {
                            Id = 27,
                            IsColonized = false,
                            PlanetId = 9
                        },
                        new
                        {
                            Id = 28,
                            IsColonized = false,
                            PlanetId = 10
                        },
                        new
                        {
                            Id = 29,
                            IsColonized = false,
                            PlanetId = 10
                        },
                        new
                        {
                            Id = 30,
                            IsColonized = false,
                            PlanetId = 10
                        },
                        new
                        {
                            Id = 31,
                            IsColonized = false,
                            PlanetId = 11
                        },
                        new
                        {
                            Id = 32,
                            IsColonized = false,
                            PlanetId = 11
                        },
                        new
                        {
                            Id = 33,
                            IsColonized = false,
                            PlanetId = 11
                        },
                        new
                        {
                            Id = 34,
                            IsColonized = false,
                            PlanetId = 12
                        },
                        new
                        {
                            Id = 35,
                            IsColonized = false,
                            PlanetId = 12
                        },
                        new
                        {
                            Id = 36,
                            IsColonized = false,
                            PlanetId = 12
                        },
                        new
                        {
                            Id = 37,
                            IsColonized = false,
                            PlanetId = 13
                        },
                        new
                        {
                            Id = 38,
                            IsColonized = false,
                            PlanetId = 13
                        },
                        new
                        {
                            Id = 39,
                            IsColonized = false,
                            PlanetId = 13
                        },
                        new
                        {
                            Id = 40,
                            IsColonized = false,
                            PlanetId = 14
                        },
                        new
                        {
                            Id = 41,
                            IsColonized = false,
                            PlanetId = 14
                        },
                        new
                        {
                            Id = 42,
                            IsColonized = false,
                            PlanetId = 14
                        },
                        new
                        {
                            Id = 43,
                            IsColonized = false,
                            PlanetId = 15
                        },
                        new
                        {
                            Id = 44,
                            IsColonized = false,
                            PlanetId = 15
                        },
                        new
                        {
                            Id = 45,
                            IsColonized = false,
                            PlanetId = 15
                        },
                        new
                        {
                            Id = 46,
                            IsColonized = false,
                            PlanetId = 16
                        },
                        new
                        {
                            Id = 47,
                            IsColonized = false,
                            PlanetId = 16
                        },
                        new
                        {
                            Id = 48,
                            IsColonized = false,
                            PlanetId = 16
                        },
                        new
                        {
                            Id = 49,
                            IsColonized = false,
                            PlanetId = 17
                        },
                        new
                        {
                            Id = 50,
                            IsColonized = false,
                            PlanetId = 17
                        },
                        new
                        {
                            Id = 51,
                            IsColonized = false,
                            PlanetId = 17
                        },
                        new
                        {
                            Id = 52,
                            IsColonized = false,
                            PlanetId = 18
                        },
                        new
                        {
                            Id = 53,
                            IsColonized = false,
                            PlanetId = 18
                        },
                        new
                        {
                            Id = 54,
                            IsColonized = false,
                            PlanetId = 18
                        },
                        new
                        {
                            Id = 55,
                            IsColonized = false,
                            PlanetId = 19
                        },
                        new
                        {
                            Id = 56,
                            IsColonized = false,
                            PlanetId = 19
                        },
                        new
                        {
                            Id = 57,
                            IsColonized = false,
                            PlanetId = 19
                        },
                        new
                        {
                            Id = 58,
                            IsColonized = false,
                            PlanetId = 20
                        },
                        new
                        {
                            Id = 59,
                            IsColonized = false,
                            PlanetId = 20
                        },
                        new
                        {
                            Id = 60,
                            IsColonized = false,
                            PlanetId = 20
                        },
                        new
                        {
                            Id = 61,
                            IsColonized = false,
                            PlanetId = 21
                        },
                        new
                        {
                            Id = 62,
                            IsColonized = false,
                            PlanetId = 21
                        },
                        new
                        {
                            Id = 63,
                            IsColonized = false,
                            PlanetId = 21
                        },
                        new
                        {
                            Id = 64,
                            IsColonized = false,
                            PlanetId = 22
                        },
                        new
                        {
                            Id = 65,
                            IsColonized = false,
                            PlanetId = 22
                        },
                        new
                        {
                            Id = 66,
                            IsColonized = false,
                            PlanetId = 22
                        },
                        new
                        {
                            Id = 67,
                            IsColonized = false,
                            PlanetId = 23
                        },
                        new
                        {
                            Id = 68,
                            IsColonized = false,
                            PlanetId = 23
                        },
                        new
                        {
                            Id = 69,
                            IsColonized = false,
                            PlanetId = 23
                        },
                        new
                        {
                            Id = 70,
                            IsColonized = false,
                            PlanetId = 24
                        },
                        new
                        {
                            Id = 71,
                            IsColonized = false,
                            PlanetId = 24
                        },
                        new
                        {
                            Id = 72,
                            IsColonized = false,
                            PlanetId = 24
                        },
                        new
                        {
                            Id = 73,
                            IsColonized = false,
                            PlanetId = 25
                        },
                        new
                        {
                            Id = 74,
                            IsColonized = false,
                            PlanetId = 25
                        },
                        new
                        {
                            Id = 75,
                            IsColonized = false,
                            PlanetId = 25
                        },
                        new
                        {
                            Id = 76,
                            IsColonized = false,
                            PlanetId = 26
                        },
                        new
                        {
                            Id = 77,
                            IsColonized = false,
                            PlanetId = 26
                        },
                        new
                        {
                            Id = 78,
                            IsColonized = false,
                            PlanetId = 26
                        },
                        new
                        {
                            Id = 79,
                            IsColonized = false,
                            PlanetId = 27
                        },
                        new
                        {
                            Id = 80,
                            IsColonized = false,
                            PlanetId = 27
                        },
                        new
                        {
                            Id = 81,
                            IsColonized = false,
                            PlanetId = 27
                        },
                        new
                        {
                            Id = 82,
                            IsColonized = false,
                            PlanetId = 28
                        },
                        new
                        {
                            Id = 83,
                            IsColonized = false,
                            PlanetId = 28
                        },
                        new
                        {
                            Id = 84,
                            IsColonized = false,
                            PlanetId = 28
                        },
                        new
                        {
                            Id = 85,
                            IsColonized = false,
                            PlanetId = 29
                        },
                        new
                        {
                            Id = 86,
                            IsColonized = false,
                            PlanetId = 29
                        },
                        new
                        {
                            Id = 87,
                            IsColonized = false,
                            PlanetId = 29
                        },
                        new
                        {
                            Id = 88,
                            IsColonized = false,
                            PlanetId = 30
                        },
                        new
                        {
                            Id = 89,
                            IsColonized = false,
                            PlanetId = 30
                        },
                        new
                        {
                            Id = 90,
                            IsColonized = false,
                            PlanetId = 30
                        },
                        new
                        {
                            Id = 91,
                            IsColonized = false,
                            PlanetId = 31
                        },
                        new
                        {
                            Id = 92,
                            IsColonized = false,
                            PlanetId = 31
                        },
                        new
                        {
                            Id = 93,
                            IsColonized = false,
                            PlanetId = 31
                        },
                        new
                        {
                            Id = 94,
                            IsColonized = false,
                            PlanetId = 32
                        },
                        new
                        {
                            Id = 95,
                            IsColonized = false,
                            PlanetId = 32
                        },
                        new
                        {
                            Id = 96,
                            IsColonized = false,
                            PlanetId = 32
                        },
                        new
                        {
                            Id = 97,
                            IsColonized = false,
                            PlanetId = 33
                        },
                        new
                        {
                            Id = 98,
                            IsColonized = false,
                            PlanetId = 33
                        },
                        new
                        {
                            Id = 99,
                            IsColonized = false,
                            PlanetId = 33
                        },
                        new
                        {
                            Id = 100,
                            IsColonized = false,
                            PlanetId = 34
                        },
                        new
                        {
                            Id = 101,
                            IsColonized = false,
                            PlanetId = 34
                        },
                        new
                        {
                            Id = 102,
                            IsColonized = false,
                            PlanetId = 34
                        },
                        new
                        {
                            Id = 103,
                            IsColonized = false,
                            PlanetId = 35
                        },
                        new
                        {
                            Id = 104,
                            IsColonized = false,
                            PlanetId = 35
                        },
                        new
                        {
                            Id = 105,
                            IsColonized = false,
                            PlanetId = 35
                        },
                        new
                        {
                            Id = 106,
                            IsColonized = false,
                            PlanetId = 36
                        },
                        new
                        {
                            Id = 107,
                            IsColonized = false,
                            PlanetId = 36
                        },
                        new
                        {
                            Id = 108,
                            IsColonized = false,
                            PlanetId = 36
                        },
                        new
                        {
                            Id = 109,
                            IsColonized = false,
                            PlanetId = 37
                        },
                        new
                        {
                            Id = 110,
                            IsColonized = false,
                            PlanetId = 37
                        },
                        new
                        {
                            Id = 111,
                            IsColonized = false,
                            PlanetId = 37
                        },
                        new
                        {
                            Id = 112,
                            IsColonized = false,
                            PlanetId = 38
                        },
                        new
                        {
                            Id = 113,
                            IsColonized = false,
                            PlanetId = 38
                        },
                        new
                        {
                            Id = 114,
                            IsColonized = false,
                            PlanetId = 38
                        },
                        new
                        {
                            Id = 115,
                            IsColonized = false,
                            PlanetId = 39
                        },
                        new
                        {
                            Id = 116,
                            IsColonized = false,
                            PlanetId = 39
                        },
                        new
                        {
                            Id = 117,
                            IsColonized = false,
                            PlanetId = 39
                        },
                        new
                        {
                            Id = 118,
                            IsColonized = false,
                            PlanetId = 40
                        },
                        new
                        {
                            Id = 119,
                            IsColonized = false,
                            PlanetId = 40
                        },
                        new
                        {
                            Id = 120,
                            IsColonized = false,
                            PlanetId = 40
                        },
                        new
                        {
                            Id = 121,
                            IsColonized = false,
                            PlanetId = 41
                        },
                        new
                        {
                            Id = 122,
                            IsColonized = false,
                            PlanetId = 41
                        },
                        new
                        {
                            Id = 123,
                            IsColonized = false,
                            PlanetId = 41
                        },
                        new
                        {
                            Id = 124,
                            IsColonized = false,
                            PlanetId = 42
                        },
                        new
                        {
                            Id = 125,
                            IsColonized = false,
                            PlanetId = 42
                        },
                        new
                        {
                            Id = 126,
                            IsColonized = false,
                            PlanetId = 42
                        },
                        new
                        {
                            Id = 127,
                            IsColonized = false,
                            PlanetId = 43
                        },
                        new
                        {
                            Id = 128,
                            IsColonized = false,
                            PlanetId = 43
                        },
                        new
                        {
                            Id = 129,
                            IsColonized = false,
                            PlanetId = 43
                        },
                        new
                        {
                            Id = 130,
                            IsColonized = false,
                            PlanetId = 44
                        },
                        new
                        {
                            Id = 131,
                            IsColonized = false,
                            PlanetId = 44
                        },
                        new
                        {
                            Id = 132,
                            IsColonized = false,
                            PlanetId = 44
                        },
                        new
                        {
                            Id = 133,
                            IsColonized = false,
                            PlanetId = 45
                        },
                        new
                        {
                            Id = 134,
                            IsColonized = false,
                            PlanetId = 45
                        },
                        new
                        {
                            Id = 135,
                            IsColonized = false,
                            PlanetId = 45
                        },
                        new
                        {
                            Id = 136,
                            IsColonized = false,
                            PlanetId = 46
                        },
                        new
                        {
                            Id = 137,
                            IsColonized = false,
                            PlanetId = 46
                        },
                        new
                        {
                            Id = 138,
                            IsColonized = false,
                            PlanetId = 46
                        },
                        new
                        {
                            Id = 139,
                            IsColonized = false,
                            PlanetId = 47
                        },
                        new
                        {
                            Id = 140,
                            IsColonized = false,
                            PlanetId = 47
                        },
                        new
                        {
                            Id = 141,
                            IsColonized = false,
                            PlanetId = 47
                        },
                        new
                        {
                            Id = 142,
                            IsColonized = false,
                            PlanetId = 48
                        },
                        new
                        {
                            Id = 143,
                            IsColonized = false,
                            PlanetId = 48
                        },
                        new
                        {
                            Id = 144,
                            IsColonized = false,
                            PlanetId = 48
                        },
                        new
                        {
                            Id = 145,
                            IsColonized = false,
                            PlanetId = 49
                        },
                        new
                        {
                            Id = 146,
                            IsColonized = false,
                            PlanetId = 49
                        },
                        new
                        {
                            Id = 147,
                            IsColonized = false,
                            PlanetId = 49
                        },
                        new
                        {
                            Id = 148,
                            IsColonized = false,
                            PlanetId = 50
                        },
                        new
                        {
                            Id = 149,
                            IsColonized = false,
                            PlanetId = 50
                        },
                        new
                        {
                            Id = 150,
                            IsColonized = false,
                            PlanetId = 50
                        },
                        new
                        {
                            Id = 151,
                            IsColonized = false,
                            PlanetId = 51
                        },
                        new
                        {
                            Id = 152,
                            IsColonized = false,
                            PlanetId = 51
                        },
                        new
                        {
                            Id = 153,
                            IsColonized = false,
                            PlanetId = 51
                        },
                        new
                        {
                            Id = 154,
                            IsColonized = false,
                            PlanetId = 52
                        },
                        new
                        {
                            Id = 155,
                            IsColonized = false,
                            PlanetId = 52
                        },
                        new
                        {
                            Id = 156,
                            IsColonized = false,
                            PlanetId = 52
                        },
                        new
                        {
                            Id = 157,
                            IsColonized = false,
                            PlanetId = 53
                        },
                        new
                        {
                            Id = 158,
                            IsColonized = false,
                            PlanetId = 53
                        },
                        new
                        {
                            Id = 159,
                            IsColonized = false,
                            PlanetId = 53
                        },
                        new
                        {
                            Id = 160,
                            IsColonized = false,
                            PlanetId = 54
                        },
                        new
                        {
                            Id = 161,
                            IsColonized = false,
                            PlanetId = 54
                        },
                        new
                        {
                            Id = 162,
                            IsColonized = false,
                            PlanetId = 54
                        },
                        new
                        {
                            Id = 163,
                            IsColonized = false,
                            PlanetId = 55
                        },
                        new
                        {
                            Id = 164,
                            IsColonized = false,
                            PlanetId = 55
                        },
                        new
                        {
                            Id = 165,
                            IsColonized = false,
                            PlanetId = 55
                        },
                        new
                        {
                            Id = 166,
                            IsColonized = false,
                            PlanetId = 56
                        },
                        new
                        {
                            Id = 167,
                            IsColonized = false,
                            PlanetId = 56
                        },
                        new
                        {
                            Id = 168,
                            IsColonized = false,
                            PlanetId = 56
                        },
                        new
                        {
                            Id = 169,
                            IsColonized = false,
                            PlanetId = 57
                        },
                        new
                        {
                            Id = 170,
                            IsColonized = false,
                            PlanetId = 57
                        },
                        new
                        {
                            Id = 171,
                            IsColonized = false,
                            PlanetId = 57
                        },
                        new
                        {
                            Id = 172,
                            IsColonized = false,
                            PlanetId = 58
                        },
                        new
                        {
                            Id = 173,
                            IsColonized = false,
                            PlanetId = 58
                        },
                        new
                        {
                            Id = 174,
                            IsColonized = false,
                            PlanetId = 58
                        },
                        new
                        {
                            Id = 175,
                            IsColonized = false,
                            PlanetId = 59
                        },
                        new
                        {
                            Id = 176,
                            IsColonized = false,
                            PlanetId = 59
                        },
                        new
                        {
                            Id = 177,
                            IsColonized = false,
                            PlanetId = 59
                        },
                        new
                        {
                            Id = 178,
                            IsColonized = false,
                            PlanetId = 60
                        },
                        new
                        {
                            Id = 179,
                            IsColonized = false,
                            PlanetId = 60
                        },
                        new
                        {
                            Id = 180,
                            IsColonized = false,
                            PlanetId = 60
                        });
                });

            modelBuilder.Entity("Nexus.Domain.Entities.RegionStructure", b =>
                {
                    b.Property<int>("StructureId")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("StructureId", "RegionId");

                    b.HasIndex("RegionId");

                    b.ToTable("RegionStructures", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Resources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MINERALS",
                            Description = "Minerals extracted from the planetary crust. They are the most abundant resource and are mainly used for the creation of structures and ships.",
                            Name = "Minerals"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MICROCHIPS",
                            Description = "Technological materials designed and created with high technology. They are used to a lesser extent than minerals.",
                            Name = "Microchips"
                        },
                        new
                        {
                            Id = 3,
                            Code = "HYDROGEN",
                            Description = "The main fuel for spaceships and is needed in smaller amounts by buildings and ships.",
                            Name = "Hydrogen"
                        },
                        new
                        {
                            Id = 4,
                            Code = "FOOD",
                            Description = "Represents the food supplies. They are necessary to keep the population alive.",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 5,
                            Code = "POPULATION",
                            Description = "The number of inhabitants in each region.",
                            Name = "Population"
                        },
                        new
                        {
                            Id = 6,
                            Code = "CREDITS",
                            Description = "The total money of the empire, obtained from trade treaties, taxes, and conquests. Credits are used to recruit troops, research, and close trade agreements.",
                            Name = "Credits"
                        });
                });

            modelBuilder.Entity("Nexus.Domain.Entities.SolarSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SolarSystems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Solar System 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Solar System 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Solar System 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Solar System 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Solar System 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Solar System 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Solar System 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Solar System 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Solar System 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Solar System 10"
                        });
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Structure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<short?>("MineId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MineId");

                    b.ToTable("Structures", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Mine", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Resource", "Resource")
                        .WithMany("Mines")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Planet", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.SolarSystem", "SolarSystem")
                        .WithMany("Planets")
                        .HasForeignKey("SolarSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarSystem");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Region", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Planet", "Planet")
                        .WithMany("Regions")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany("Regions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Planet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.RegionStructure", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Region", "Region")
                        .WithMany("RegionStructures")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.Domain.Entities.Structure", "Structure")
                        .WithMany()
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Structure", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Mine", "Mine")
                        .WithMany()
                        .HasForeignKey("MineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Mine");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Planet", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Region", b =>
                {
                    b.Navigation("RegionStructures");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Resource", b =>
                {
                    b.Navigation("Mines");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.SolarSystem", b =>
                {
                    b.Navigation("Planets");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.User", b =>
                {
                    b.Navigation("Regions");
                });
#pragma warning restore 612, 618
        }
    }
}
